#!/usr/bin/env node
import { execSync } from "child_process";

const sampleImages = [
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
  "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
  "https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?w=800&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
];

const houses = [
  {
    id: 1,
    address: "1247 Meridian Ave",
    city: "South Pasadena, CA 91030",
    price: 1285000,
    beds: 3,
    baths: 2,
    sqft: 1840,
    yearBuilt: 1928,
    status: "interested",
    favorite: true,
    images: sampleImages.slice(0, 10),
    neighborhood: "Charming tree-lined streets with a strong sense of community. Walking distance to Mission Street shops and restaurants.",
    sidewalks: true,
    streetTrees: true,
    parkProximity: "0.3 miles to Garfield Park",
    floodRisk: "Low",
    fireRisk: "Low",
    crimeRating: "Very Low \u2014 Grade A (CrimeGrade.org)",
    distances: [
      { name: "Whole Foods Market", miles: "3.2 mi", time: "9 min" },
      { name: "Trader Joe's", miles: "1.8 mi", time: "6 min" },
      { name: "Costco", miles: "5.1 mi", time: "14 min" },
      { name: "Target", miles: "2.4 mi", time: "8 min" },
      { name: "Home Depot", miles: "3.7 mi", time: "11 min" },
      { name: "Republik Coffee", miles: "2.1 mi", time: "7 min" },
    ],
    agent: { name: "Sarah Chen", phone: "(626) 555-0142", email: "sarah@realestate.com" },
    dateListed: "2026-01-15",
    priceHistory: [
      { type: "listed", label: "Listed", date: "Jan 15, 2026", amount: 1325000 },
      { type: "reduced", label: "Price Reduced", date: "Feb 12, 2026", amount: 1285000 },
    ],
    lastSold: { date: "Mar 2018", price: 895000 },
    estimates: { zillow: 1310000, redfin: 1275000 },
    redfinUrl: "#",
    zillowUrl: "#",
    notes: "Love the craftsman details. Kitchen needs updating but great bones. Garage converted to ADU potential.",
  },
  {
    id: 2,
    address: "892 Oak Knoll Terrace",
    city: "Pasadena, CA 91106",
    price: 1695000,
    beds: 4,
    baths: 3,
    sqft: 2450,
    yearBuilt: 1936,
    status: "visited",
    favorite: false,
    images: [sampleImages[1], ...sampleImages.slice(3)],
    neighborhood: "Prestigious Oak Knoll area. Large lots, mature trees, quiet and private. Near Caltech and Huntington Library.",
    sidewalks: true,
    streetTrees: true,
    parkProximity: "0.5 miles to Lacy Park",
    floodRisk: "Low",
    fireRisk: "Low",
    crimeRating: "Low \u2014 Grade A- (CrimeGrade.org)",
    distances: [
      { name: "Whole Foods Market", miles: "2.1 mi", time: "7 min" },
      { name: "Trader Joe's", miles: "1.2 mi", time: "4 min" },
      { name: "Costco", miles: "4.8 mi", time: "13 min" },
      { name: "Target", miles: "1.9 mi", time: "6 min" },
      { name: "Home Depot", miles: "3.2 mi", time: "10 min" },
      { name: "Republik Coffee", miles: "1.4 mi", time: "5 min" },
    ],
    agent: { name: "Michael Torres", phone: "(626) 555-0287", email: "michael@luxuryrealty.com" },
    dateListed: "2025-12-08",
    priceHistory: [
      { type: "listed", label: "Listed", date: "Dec 8, 2025", amount: 1750000 },
      { type: "reduced", label: "Price Reduced", date: "Jan 20, 2026", amount: 1695000 },
    ],
    lastSold: { date: "Jun 2015", price: 1120000 },
    estimates: { zillow: 1720000, redfin: 1685000 },
    redfinUrl: "#",
    zillowUrl: "#",
    notes: "",
  },
  {
    id: 3,
    address: "345 Marengo Ave",
    city: "Pasadena, CA 91101",
    price: 975000,
    beds: 2,
    baths: 2,
    sqft: 1320,
    yearBuilt: 1952,
    status: "new",
    favorite: false,
    images: [sampleImages[2], sampleImages[0], ...sampleImages.slice(4)],
    neighborhood: "Central Pasadena near Old Town. Urban feel with easy access to dining, shopping, and the Gold Line.",
    sidewalks: null,
    streetTrees: null,
    parkProximity: "0.2 miles to Memorial Park",
    floodRisk: "Low",
    fireRisk: "Low",
    crimeRating: "Moderate \u2014 Grade B (CrimeGrade.org)",
    distances: [
      { name: "Whole Foods Market", miles: "0.8 mi", time: "3 min" },
      { name: "Trader Joe's", miles: "0.6 mi", time: "2 min" },
      { name: "Costco", miles: "3.9 mi", time: "11 min" },
      { name: "Target", miles: "0.5 mi", time: "2 min" },
      { name: "Home Depot", miles: "2.8 mi", time: "9 min" },
      { name: "Republik Coffee", miles: "0.3 mi", time: "2 min" },
    ],
    agent: { name: "Lisa Park", phone: "(626) 555-0391", email: "lisa@pasadenarealty.com" },
    dateListed: "2026-02-28",
    priceHistory: [
      { type: "listed", label: "Listed", date: "Feb 28, 2026", amount: 975000 },
    ],
    lastSold: { date: "Aug 2020", price: 780000 },
    estimates: { zillow: 990000, redfin: 965000 },
    redfinUrl: "#",
    zillowUrl: "#",
    notes: "",
  },
  {
    id: 4,
    address: "1589 La Loma Rd",
    city: "Pasadena, CA 91105",
    price: 2150000,
    beds: 5,
    baths: 4,
    sqft: 3200,
    yearBuilt: 1922,
    status: "offer",
    favorite: true,
    images: [sampleImages[3], sampleImages[1], sampleImages[5], ...sampleImages.slice(6)],
    neighborhood: "Linda Vista area with sweeping views of the Arroyo Seco. Historic homes, large lots, hiking access.",
    sidewalks: false,
    streetTrees: true,
    parkProximity: "0.1 miles to Lower Arroyo Park, direct trail access",
    floodRisk: "Low",
    fireRisk: "Moderate \u2014 adjacent to wildland-urban interface",
    crimeRating: "Very Low \u2014 Grade A+ (CrimeGrade.org)",
    distances: [
      { name: "Whole Foods Market", miles: "2.8 mi", time: "8 min" },
      { name: "Trader Joe's", miles: "1.9 mi", time: "6 min" },
      { name: "Costco", miles: "5.4 mi", time: "15 min" },
      { name: "Target", miles: "2.6 mi", time: "8 min" },
      { name: "Home Depot", miles: "3.9 mi", time: "12 min" },
      { name: "Republik Coffee", miles: "2.3 mi", time: "7 min" },
    ],
    agent: { name: "David Kim", phone: "(626) 555-0518", email: "david@aroyorealty.com" },
    dateListed: "2025-11-20",
    priceHistory: [
      { type: "listed", label: "Listed", date: "Nov 20, 2025", amount: 2295000 },
      { type: "reduced", label: "Price Reduced", date: "Dec 18, 2025", amount: 2200000 },
      { type: "reduced", label: "Price Reduced", date: "Feb 1, 2026", amount: 2150000 },
    ],
    lastSold: { date: "Apr 2012", price: 1450000 },
    estimates: { zillow: 2180000, redfin: 2125000 },
    redfinUrl: "#",
    zillowUrl: "#",
    notes: "Submitted offer at $2.1M. Agent says sellers are motivated. Inspection scheduled for March 10.",
  },
  {
    id: 5,
    address: "2034 Monte Vista St",
    city: "Altadena, CA 91001",
    price: 1125000,
    beds: 3,
    baths: 2,
    sqft: 1680,
    yearBuilt: 1947,
    status: "interested",
    favorite: false,
    images: [sampleImages[4], sampleImages[2], sampleImages[7], ...sampleImages.slice(0, 4)],
    neighborhood: "Quiet Altadena neighborhood with mountain views. Close to Eaton Canyon trails. Unincorporated LA County.",
    sidewalks: null,
    streetTrees: null,
    parkProximity: "0.8 miles to Eaton Canyon Nature Center",
    floodRisk: "Low",
    fireRisk: "High \u2014 very high fire hazard severity zone",
    crimeRating: "Low \u2014 Grade B+ (CrimeGrade.org)",
    distances: [
      { name: "Whole Foods Market", miles: "4.1 mi", time: "12 min" },
      { name: "Trader Joe's", miles: "3.2 mi", time: "9 min" },
      { name: "Costco", miles: "6.3 mi", time: "17 min" },
      { name: "Target", miles: "3.8 mi", time: "11 min" },
      { name: "Home Depot", miles: "4.5 mi", time: "13 min" },
      { name: "Republik Coffee", miles: "3.6 mi", time: "10 min" },
    ],
    agent: { name: "Jennifer Walsh", phone: "(626) 555-0673", email: "jen@altadenarealty.com" },
    dateListed: "2026-02-10",
    priceHistory: [
      { type: "listed", label: "Listed", date: "Feb 10, 2026", amount: 1125000 },
    ],
    lastSold: { date: "Jan 2019", price: 825000 },
    estimates: { zillow: 1140000, redfin: 1110000 },
    redfinUrl: "#",
    zillowUrl: "#",
    notes: "",
  },
  {
    id: 6,
    address: "478 Bellefontaine St",
    city: "Pasadena, CA 91105",
    price: 1475000,
    beds: 4,
    baths: 2.5,
    sqft: 2100,
    yearBuilt: 1915,
    status: "rejected",
    favorite: false,
    images: [sampleImages[5], sampleImages[8], sampleImages[9], ...sampleImages.slice(0, 5)],
    neighborhood: "Historic Bungalow Heaven landmark district. Walkable to shops on Lake Ave. Strong neighborhood association.",
    sidewalks: true,
    streetTrees: false,
    parkProximity: "0.4 miles to McDonald Park",
    floodRisk: "Low",
    fireRisk: "Low",
    crimeRating: "Low \u2014 Grade A- (CrimeGrade.org)",
    distances: [
      { name: "Whole Foods Market", miles: "1.5 mi", time: "5 min" },
      { name: "Trader Joe's", miles: "0.9 mi", time: "3 min" },
      { name: "Costco", miles: "4.2 mi", time: "12 min" },
      { name: "Target", miles: "1.3 mi", time: "4 min" },
      { name: "Home Depot", miles: "2.1 mi", time: "7 min" },
      { name: "Republik Coffee", miles: "1.7 mi", time: "6 min" },
    ],
    agent: { name: "Robert Chang", phone: "(626) 555-0824", email: "robert@historichomes.com" },
    dateListed: "2025-10-05",
    priceHistory: [
      { type: "listed", label: "Listed", date: "Oct 5, 2025", amount: 1550000 },
      { type: "reduced", label: "Price Reduced", date: "Nov 22, 2025", amount: 1500000 },
      { type: "reduced", label: "Price Reduced", date: "Jan 8, 2026", amount: 1475000 },
    ],
    lastSold: { date: "Sep 2016", price: 1050000 },
    estimates: { zillow: 1490000, redfin: 1460000 },
    redfinUrl: "#",
    zillowUrl: "#",
    notes: "Foundation issues found during inspection. Too costly to repair. Passing.",
  },
];

// Determine if we're targeting production or local/preview
const isProduction = process.argv.includes("--env") && process.argv.includes("production");
const bindingFlag = isProduction ? "--preview false" : "--local --preview";

console.log(`Seeding ${houses.length} houses to ${isProduction ? "PRODUCTION" : "LOCAL"} KV...`);

for (const house of houses) {
  const key = `house:${house.id}`;
  const value = JSON.stringify(house);
  const cmd = `npx wrangler kv key put --binding HOUSES ${bindingFlag} "${key}" '${value.replace(/'/g, "'\\''")}'`;
  try {
    execSync(cmd, { stdio: "inherit", cwd: process.cwd() });
    console.log(`  Seeded: ${house.address}`);
  } catch (err) {
    console.error(`  Failed: ${house.address}`, err.message);
  }
}

console.log("Done!");
